-- Migración de tablas para el sistema IDEAL a Supabase

-- 1. Tabla de Perfiles (Extensión de Auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('admin', 'vendedor', 'viewer')) DEFAULT 'vendedor',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Tabla de Productos
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  category_label TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT,
  image TEXT,
  badge TEXT,
  is_custom BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Tabla de Ventas
CREATE TABLE sales (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  client_name TEXT NOT NULL,
  client_phone TEXT,
  client_email TEXT,
  vendor_id UUID REFERENCES profiles(id),
  vendor_name TEXT,
  subtotal DECIMAL(10,2) NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  payment_type TEXT CHECK (payment_type IN ('full', 'credit')) NOT NULL,
  paid_amount DECIMAL(10,2) DEFAULT 0,
  remaining_amount DECIMAL(10,2) NOT NULL,
  status TEXT CHECK (status IN ('pending', 'partial', 'completed')) DEFAULT 'pending',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Ítems de la Venta (Relación muchos a muchos entre Ventas y Productos)
CREATE TABLE sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id UUID REFERENCES sales(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price_at_sale DECIMAL(10,2) NOT NULL
);

-- 5. Historial de Pagos (Para ventas a crédito)
CREATE TABLE payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  sale_id UUID REFERENCES sales(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  method TEXT,
  notes TEXT,
  payment_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- INSERTAR DATOS INICIALES DE PRODUCTOS
INSERT INTO products (name, category, category_label, price, description, image, badge)
VALUES 
('Kit de Higiene', 'aseo', 'Aseo personal', 12.5, 'Kit completo de higiene personal, ideal para el cuidado diario de toda la familia.', 'https://conecaideal.com/wp-content/uploads/2023/05/1v2.png', 'Kit'),
('Kit de Limpieza', 'limpieza', 'Limpieza', 12.5, 'Kit esencial para mantener tu hogar limpio y desinfectado con los mejores productos.', 'https://conecaideal.com/wp-content/uploads/2023/05/2.png', 'Kit'),
('Jabón de Azufre', 'cuidado', 'Cuidado personal', 5, 'Jabón de azufre con propiedades purificantes, ideal para piel grasa y con impurezas.', '/legacy/img/jabon-azufre.jpeg', NULL),
('Jabón de Glicerina', 'cuidado', 'Cuidado personal', 5, 'Jabón suave con glicerina, hidrata y protege la piel en cada lavado.', '/legacy/img/jabon-glicerina.jpeg', NULL),
('Acondicionador', 'aseo', 'Aseo personal', 8.5, 'Acondicionador nutritivo para cabello suave, brillante y fácil de peinar.', '/legacy/img/acondicionador.png', NULL),
('Champú de Niño', 'aseo', 'Aseo personal', 8.5, 'Fórmula suave sin lágrimas, especialmente diseñada para el cabello de los más pequeños.', '/legacy/img/shampoo-kids.jpeg', 'Bebés'),
('Gel de Árnica', 'cuidado', 'Cuidado personal', 9, 'Gel con extracto de árnica, alivia golpes, contusiones y dolores musculares.', '/legacy/img/gel-arnica.jpeg', NULL),
('Protector Solar', 'cuidado', 'Cuidado personal', 10, 'Protección solar de amplio espectro para el cuidado diario de tu piel bajo el sol.', '/legacy/img/protector-solar.jpeg', 'Nuevo'),
('Lavaplatos en Crema', 'limpieza', 'Limpieza', 5, 'Crema lavaplatos de alta eficacia, elimina grasa y deja tus utensilios impecables.', 'https://conecaideal.com/wp-content/uploads/2023/03/shampoo-ideal-4-1372x2048.jpg', NULL),
('Alisado Orgánico', 'cuidado', 'Cuidado personal', 20, 'Tratamiento alisador con ingredientes orgánicos para un cabello liso, sano y brillante.', '/legacy/img/alisado-organico.jpeg', 'Premium'),
('Jabón Íntimo', 'aseo', 'Aseo personal', 9, 'Jabón íntimo con pH balanceado, fórmula suave para una higiene segura y delicada.', '/legacy/img/jabon-intimo.jpeg', NULL);

-- HABILITAR RLS (Row Level Security)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS BÁSICAS (Lectura pública para productos, privada para el resto)
CREATE POLICY "Productos visibles para todos" ON products FOR SELECT USING (true);
CREATE POLICY "Permitir todo a autenticados en products" ON products FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Perfiles editables por el propio usuario" ON profiles FOR ALL USING (auth.uid() = id);

-- POLÍTICAS PARA VENTAS Y PAGOS (Solo usuarios autenticados)
CREATE POLICY "Permitir todo a autenticados en sales" ON sales FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Permitir todo a autenticados en sale_items" ON sale_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Permitir todo a autenticados en payments" ON payments FOR ALL USING (auth.role() = 'authenticated');
